### ISSUE TITLE
Model with List field of self type adds "List" under definitions in spec

### ISSUE THREAD

**Issue by sudohippie** [swagger-api/swagger-core#1131]
Given a model:

```java
@ApiModel(description = "Foo class")
public class Foo {

    @ApiModelProperty(required = true, value = "some content")
    private List<Foo> foos;

    public List<Foo> getFoos() {
        return foos;
    }

    public void setFoos(List<Foo> foos) {
        this.foos = foos;
    }
}
```

The expected definition in the spec is:

```json
"definitions" : {
    "Foo" : {
      "required" : [ "foos" ],
      "properties" : {
        "checks" : {
          "type" : "array",
          "description" : "some content",
          "items" : {
            "$ref" : "#/definitions/Foo"
          }
        }
      },
      "description" : "Foo class"
    }
  }
```
However, we are seeing:

```json
"definitions" : {
    "Foo" : {
      "required" : [ "foos" ],
      "properties" : {
        "checks" : {
          "type" : "array",
          "description" : "some content",
          "items" : {
            "$ref" : "#/definitions/Foo"
          }
        }
      },
      "description" : "Foo class"
    },
    "List" : {
      "properties" : {
        "empty" : {
          "type" : "boolean",
          "default" : false
        }
      }
    }
  }
```

Note the additional ```List``` definition. The code works just fine (as expected) if the field contains List of non ```Foo```:

``` java
@ApiModelProperty(required = true, value = "some content")
private List<Bar> bars;
```

Up on some initial debugging: I noticed that this issue occurs when ```Foo``` model is in the process of being resolved (```ModelConverterContextImpl.processedTypes``` has an entry but ```ModelConverterContextImpl.modelByType``` doesn't have an entry yet). ```ModelResolver``` at Line 123 requests for the ```Model``` of the inner type of the List (in this scenario, the unresolved ```Foo```) but a ```null``` is returned. This leads to treating the ```List``` as a "complex type".

It is very likely this issue will re-appear if ```Bar``` Class has a List of```Foo``` (cyclic reference)

```java
@ApiModel(description = "Foo class")
public class Foo {

    @ApiModelProperty(required = true, value = "some content")
    private List<Bar> bars;

    public List<Bar> getBars() {
        return bars;
    }

    public void setBars(List<Bar> bars) {
        this.bars = bars;
    }
}
```
```java
@ApiModel(description = "Bar class")
public class Bar {

    @ApiModelProperty(required = true, value = "some content")
    private List<Foo> foos;

    public List<Foo> getFoos() {
        return foos;
    }

    public void setFoos(List<Foo> foos) {
        this.foos = foos;
    }
}
```

I must also mention that this is based on observation in the ```master``` and ```tags/1.5.1-M2``` branches.

**Comment by webron** [comment]
Can you try the develop_2.0 branch? It's available as a snapshot, but would require a little extra work as we've repackaged the project as io.swagger instead of com.wordnik. Snapshot version is 1.5.0-SNAPSHOT.

**Comment by sudohippie** [comment]
Okay. I'll take a look at develop_2.0.

**Comment by sudohippie** [comment]
cloned develop_2.0 and ran ```mvn clean install```. Got a build failure related to code coverage:
```
[INFO] --- jacoco-maven-plugin:0.7.2.201409121644:check (default-check) @ swagger-jersey-jaxrs ---
[INFO] Analyzed bundle 'swagger-jersey-jaxrs' with 1 classes
[WARNING] Rule violated for bundle swagger-jersey-jaxrs: complexity covered ratio is 0.00, but expected minimum is 0.90
[WARNING] Rule violated for bundle swagger-jersey-jaxrs: classes missed count is 1, but expected maximum is 0
[WARNING] Rule violated for class io.swagger.jersey.SwaggerJerseyJaxrs: lines covered ratio is 0.00, but expected minimum is 0.90
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.440s
[INFO] Finished at: Fri Jun 05 11:11:45 PDT 2015
[INFO] Final Memory: 32M/327M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.7.2.201409121644:check (default-check) on project swagger-jersey-jaxrs: Coverage checks have not been met. See log for details. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

The code install fine with ```mvn clean install -DskipTests```.

Travis-CI seems to be building fine. But I see swagger-jersey-jaxrs/target/jacoco.exec which Travis can not find:

```
[INFO] --- jacoco-maven-plugin:0.7.2.201409121644:check (default-check) @ swagger-jersey-jaxrs ---
[INFO] Skipping JaCoCo execution due to missing execution data file:/home/travis/build/swagger-api/swagger-core/modules/swagger-jersey-jaxrs/target/jacoco.exec
```

**Comment by webron** [comment]
@sudohippie - heh, we don't really have jacoco installed so it never fails for us, but since it's code coverage, that doesn't affect functionality. We're looking into 'fixing' it, but for now, please skip it and check the original issue.

**Comment by olensmar** [comment]
Seems to work for self references but not for circular references - i.e. as in the Foo / Bar classes above - in that case the "top level" reference works but the reference to the contained class that refs back to the top-level class gets a List definition. I'll continue digging...

**Comment by tomtit** [comment]
Looks like fixed at the `develop_2.0` branch after the #1130 PR.

**Comment by olensmar** [comment]
Thanks, I'll confirm later today!

**Comment by olensmar** [comment]
confirmed - seems to work in develop branch - closing!

**Comment by mortias** [comment]
@olensmar please check this related issue, https://github.com/swagger-api/swagger-core/issues/1178 i think it's related but not completely solved
