### ISSUE TITLE
range support for @ApiModelProperty's allowableValues

### ISSUE THREAD

**Issue by mar612** [swagger-api/swagger-core#1276]
I tried to specify a range of allowable numeric values using @ApiModelProperty's allowableValues, but it doesn't seem to show up at all in my swagger json.  I've tried using both 1.5.0 and 1.5.1-SNAPSHOT, with no success.  I found an old closed issue on the subject, which would seem to indicate it was fixed (but maybe not) ?  Is there a newer snapshot I should be using?  Thanks!

**Comment by webron** [comment]
Can you share how you define it in the code?

**Comment by mar612** [comment]
Here's the code for my model:

```java
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel
public class User {
    @ApiModelProperty(value = "user id", allowableValues = "range[1, 3]")
    private int userId;

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }
}
```

**Comment by webron** [comment]
I'm afraid you've hit a bug.

**Comment by mar612** [comment]
Okay, thanks for letting me know (and for such speedy replies)

**Comment by webron** [comment]
Fixed in develop_2.0.

**Comment by pn279j** [comment]
I am using springfox library to generate swagger documentation. it uses 2 swagger libraries - swagger-annotations and swagger-models. the latest version of swagger-annotations (1.5.2) does not seem to fix the issue. Is the fix available there? thanks!

**Comment by webron** [comment]
However springfox utilizes the annotations is up to them. You'd need to ask them about it.

**Comment by hiejulia** [comment]
Same problem with `swagger-jersey2-jaxrs` any idea ?
