### ISSUE TITLE
Error log when dataType is "file" in @ApiImplicitParam (swagger-jaxrs)

### ISSUE THREAD

**Issue by agusgr** [swagger-api/swagger-core#1319]
Hi all,

Working with version 1.5.1, I get an error trace[1] when I set "file" as the dataType in an ApiImplicitParam annotation.

Seems like the problem is in the method "typeFromString" in https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/ReflectionUtils.java

Maybe "file" should be in PrimitiveType ?

Changing dataType to java.io.File the error dissapeared but the file input also dissapeared from the UI and I cannot perform multipart post.

[1] ERROR [io.swagger.jaxrs.utils.ReflectionUtils] Failed to resolve 'file' into class: java.lang.ClassNotFoundException: file from ...

**Comment by agusgr** [comment]
Hi @webron, thank you for classify it. Do you have any idea what version it will be solved?

**Comment by webron** [comment]
No idea.

**Comment by agusgr** [comment]
@webron ok, thanks for the reply. 

Do you think that adding "file" to PrimitiveType could be a good solution?

I just made the change in the develop_2.0 branch and adding file to io.swagger.converter.PrimitiveType.java solves the error log and all test are OK so if all of you agree I can send a PR

**Comment by agusgr** [comment]
I'm reading right now the announcement in the google group [1] so I suppose that it's better wait that the changes are done in the repo to be sure in what branch I have to test the changes.

Anyway, I'm available to send the PR if my proposal is correct.

[1] https://groups.google.com/forum/#!topic/swagger-swaggersocket/dEwm8J5p7Ag

**Comment by agusgr** [comment]
Hi everybody,

I know that this is not a critical bug but the fake error in the log is generating some "controversy" in our solution and it would be great if can be solved in the next release.

I suppose that the PR #1363 is yet not accepted because more test are needed or there are another issues related so if we can help doing more changes or tests, we are glad to help you.

Regards,

Agus

**Comment by fehguy** [comment]
The `dataType` field is expecting either a primitive or a fully-qualified type.  So you can certainly use `java.io.File` and it'll follow the regular processing patterns.

**Comment by agusgr** [comment]
Hi @fehguy,

Changing the dataType to java.io.File solves the log issue, but then in the swagger UI (I'm working with the 2.1.1 version) the file input dissapeared and it becomes a normal text input.

This is the JSON fragment with the definition for this input:

{
          "name" : "file",
          "in" : "formData",
          "description" : "File to upload",
          "required" : true,
          "type" : "java.io.File"
        }

Should I open an issue in the swagger-ui project? 

Thanks!!

**Comment by fehguy** [comment]
hmm.  Can you please change the input type to java.io.InputStream and let me know what you get?

**Comment by agusgr** [comment]
Hi again @fehguy,

With java.io.InputStream as dataType I get the same situation. There are no error in the log but the file input in the IU is  a normal text input.

This is the generated JSON:

{
          "name" : "file",
          "in" : "formData",
          "description" : "File to upload",
          "required" : true,
          "type" : "java.io.InputStream"
        }

Let me know if you need some more testing and if I should open an issue in the UI project.

Thanks!

**Comment by fehguy** [comment]
OK I've dug into this more.  We do indeed need to make a change in the processing chain :(

**Comment by fehguy** [comment]
You can pull this from master

**Comment by agusgr** [comment]
Hi @fehguy ! 

I've  tested and works fine! (setting java.io.File as the dataType).  Do you have a date (or an aproximate idea) for the 1.5.5 release?

Thanks!

**Comment by fehguy** [comment]
Hi, I have pushed a snapshot to sonatype-snapshots repo.  For the next release, I don't have a date but I do hope to do it within a few weeks.  I apologize that we didn't get this into 1.5.4, there was just too much to do :)

**Comment by lmprice** [comment]
I can confirm that this is resolved in 1.5.6.

**Comment by fehguy** [comment]
great, thank you

**Comment by dklotz** [comment]
@fehguy I'm still seeing this error log with dataType="file" in 1.5.9. dataType="java.io.InputStream" generates no error on the server-side, but also no file chooser on the client side (also having "java.io.InputStream" in the generated swagger.json/yaml wouldn't really be helping our non-java clients). "java.io.File" on the annotation works (and results in the correct "type": "file" in the JSON), but the spec says to use "file", so maybe this should be supported on the annotation?

**Comment by fehguy** [comment]
@dklotz please share your whole annotation declaration

**Comment by dklotz** [comment]
This works:
```Java
@ApiImplicitParams({
            @ApiImplicitParam(name = UploadRequestParts.FILE, value = "The binary file to upload.", required = true, dataType = "java.io.File", paramType = "form")
})
```

This generates the error log mentioned above:
```Java
@ApiImplicitParams({
            @ApiImplicitParam(name = UploadRequestParts.FILE, value = "The binary file to upload.", required = true, dataType = "file", paramType = "form")
})
```

So the workaround works, I just thought the annotations should maybe accept the type "file" as its described in the spec.

**Comment by msiemczyk** [comment]
I don't know if this was ever pulled in or what happened but the fix for this thing is definitely not in. Was this rejected on purpose or can we still add file as primitive type?

**Comment by msiemczyk** [comment]
I've created pull request here:

https://github.com/swagger-api/swagger-core/pull/1981
