### ISSUE TITLE
BUG @Schema#implementation not processed on properties when generating open api 3.1.0

### ISSUE THREAD

**Issue by Lorenzo-Bracci** [swagger-api/swagger-core#4679]
## Problem
When generating OpenAPI 3.1.0 spec the `@Schema#implementation` value on a property is ignored.

## Expected behaviour 
`@Schema#implementation`  is considered also in OAS3.1

## Reproducer
The issues is reproduced in the following test (note that the test is successful if the model resolvers generate OAS3.0.1 instead):

```
    @Test(description = "Shows that @Schema#implementation is not propagated from property when using oas 3.1.0")
    public void testModelWithCustomSchemaImplementationInPropertyForOas31() {

        String expectedYaml = "ModelWithCustomSchemaImplementationInProperty:\n" +
                "  type: object\n" +
                "  properties:\n" +
                "    exampleField:\n" +
                // the expected type is int rather than string as we override the type with @Schema(implementation = Integer.class)
                "      type: integer\n" +
                "      format: int32\n";

        Map<String, io.swagger.v3.oas.models.media.Schema> stringSchemaMap = ModelConverters.getInstance(true).readAll(ModelWithCustomSchemaImplementationInProperty.class);

        // fails as @Schema#implementation is not processed and therefore the original property type is used (String)
        SerializationMatchers.assertEqualsToYaml31(stringSchemaMap, expectedYaml);
    }

    static class ModelWithCustomSchemaImplementationInProperty {

        @Schema(implementation = Integer.class)
        private String exampleField;

        public String getExampleField() {
            return exampleField;
        }

        public void setExampleField(String exampleField) {
            this.exampleField = exampleField;
        }

    }
```

## Investigation with proposed solution

Looking at the `ModelResolver` code, it seems that `@Schema` annotation is not propagated when attempting to resolve a model for a property (it is excluded from context annotations in `ModelResolver#682`). There is an attempt to reconcile this information at `ModelResolver#719` (through `AnnotationsUtils.getSchemaFromAnnotation`). Information from `@Schema#implementation` is not used here but I imagine that it is necessary to use this information before attempting to resolve the model rather than after as it seems central in the model resolution process. Therefore I wonder if possibly overriding the `AnnotatedType#type`  used for `context.resolve` in `ModelResolver#716` could be a proper solution for the issue?

**Comment by micryc** [comment]
Fixed by #4720, will be a part of newest release.

**Comment by arungitan** [comment]
As described in the link above from Mattias, it does not appear that this issue is fixed (as of swagger-core 2.2.36) for use of "implementation" within `@ArraySchema.schema` (regression from 3.0).
@micryc  - could you clarify if your fix also fixes the ArraySchema issue linked above?  and if yes, is the fix already available in a release / when will it be available?

**Comment by ewaostrowska** [comment]
Hi @arungitan, 
I have analyzed the behavior of ArraySchema and Schema with implementation for 3.x and 3.1.  
The behavior for 3.x is correct, but for 3.1 is incorrect. This fix is already available in the release and does not fix the ArraySchema implementation issue. I will update you about the progress in this issue[[Bug]: Regression: class specified in @ArraySchema.schema.implementation not rendered in schemas #4993](https://github.com/swagger-api/swagger-core/issues/4993)
